apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks

    spec:
      containers:
        - name: tasks
          image: pinyadapizza/kub-demo-tasks:1
          env:
            - name: AUTH_ADDRESS
              #value: "10.105.32.100"
              value: "auth-service.default"
            - name: TASKS_FOLDER
              value: tasks