apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users

    spec:
      containers:
        - name: users
          image: pinyadapizza/kub-demo-users:latest
          env:
            - name: AUTH_ADDRESS
              #value: "10.105.32.100"
              value: "auth-service.default"